### ISSUE TITLE
B+Tree  대소문자 구분 관련하여 질문있습니다

### ISSUE THREAD

**Issue by JinSeoHan** [myungoh/DS_Project_2_2021_2#1]
제안서에서 B+Tree설명에
"b+-tree 는 그림 3 의 예시와 같이 이름을 기준으로 구성하며, 대소문자를 구별하지 않는다." 라고 되어 있습니다.
그러면 insert할때 index Node에서 대소문자를 구분하지 않으면서 비교하면서 내려가는데  마지막 추가할 때 DataNode의 map에 들어갈 경우 map STL 특성상 자동으로 사전순으로 대소문자 구분하여 오름차순으로 자동 정렬이 됩니다.
그러면 map에 추가될 때 map 안에서 대소문자가 자동으로 구분이 되어 정렬되는데 IndexNode 부분에서만 대소문자 구분없이 비교하고 내려가도록 구현하고 map에 자동 정렬되는 부분은 신경쓰지 않아도 되는건가요?

**Comment by myungoh** [comment]
안녕하세요.
그 부분은 문제가 있는 것 같습니다.
b+tree는 대소문자 구별하여 진행해주세요. 
아스키 문자 코드 기준으로 구별하시면 될 거 같습니다. (대문자 < 소문자)

SEARCH_BP 명령어도 대소문자 구별하여, 결과가 나오도록 수행하시면 됩니다.
