### ISSUE TITLE
AVL Tree 대소문자 구별 질문드립니다.

### ISSUE THREAD

**Issue by chanseobx** [myungoh/DS_Project_2_2021_2#10]
b+ tree는 대소문자 구별하지 않는걸로 알고 있습니다.

AVL Tree는 b+ tree로부터 오는 데이터들인데 대소문자를 구별하지 않는다는게 어떤 의미인지 잘 모르겠습니다.

예를들어 b+ tree에 백신접종완료자 "Erin" 과 "erin"을 입력했을 때 두개의 data가 입력될거로 예상이 되는데
AVL Tree에서 대소문자를 구별하지 않는다면 이 data들은 같은 data로 해야되는건가요?

아니면 이런경우는 없다하고 b+ tree에 백신접종완료자 "Erin" 과 "erik" 을 입력했을 때 AVL Tree에서 대소문자를 구별하지 않으니 "erin"과 "erik"으로 또는 "Erin" "Erik"으로 생각해서 대소문자 구별하지않는 사전식순서로 삽입해주면 되는건가요?
이렇게 된다면 VPRINT 명령을 할 때도 대소문자 구별없이 정렬해서 출력하는 것인가요?

**Comment by myungoh** [comment]
1. 그런 경우는 고려하지 않으셔도 됩니다.
2. AVL tree에는 대소문자 구별하지 않는 사전식 순서로 삽입해주세요. VPRINT도 역시 대소문자는 구별하지 않습니다.
