### ISSUE TITLE
searchDataNode 함수 관련 질문 있습니다

### ISSUE THREAD

**Issue by jiwoo0629** [myungoh/DS_Project_2_2021_2#12]
![image](https://user-images.githubusercontent.com/90768869/140014151-89f6bc5f-7bf6-4fea-b254-34637480979b.png)
올려주신 강의자료에 따르면 data node 포인터를 반환한다고 되어있는데 skeleton 코드 상에는 BpTreeNode*를 반환하는 것으로 되어있습니다. 어떤 포인터를 반환하면 되는지 궁금합니다.

**Comment by myungoh** [comment]
주어진 skeleton 코드의 BpTreeNode*를 이용해서 data node 포인터를 반환하시면 됩니다.
