### ISSUE TITLE
2021_DS_Project2_ver6.pdf ㅁProgram implementation 질문

### ISSUE THREAD

**Issue by chanseobx** [myungoh/DS_Project_2_2021_2#14]
![image](https://user-images.githubusercontent.com/90690557/140032748-19b44417-3306-41ff-b15c-af109afd5976.png)

p.6~7 입니다.
SEARCH_AVL 명령을 설명하는중에
PRINT_ AVL Jacob 명령으로 되어있는데.. PRINT_AVL 명령도 따로 구현해야 하나요?

**Comment by myungoh** [comment]
아니요. SEARCH_AVL 만 수행하시면 됩니다.
자료 수정하겠습니다.
감사합니다.
