### ISSUE TITLE
SEARCH_BP 관련하여 질문있습니다

### ISSUE THREAD

**Issue by JinSeoHan** [myungoh/DS_Project_2_2021_2#15]
안녕하십니까 데이터구조설계 강의를 듣고있는 2018202094 한서진입니다.
![image](https://user-images.githubusercontent.com/87526189/140040957-d6d8bd1a-bbdd-41bd-8e9a-2305cba2d5f4.png)
위 사진은 SEARCH_BP 관련하여 제안서에 나와있는 출력 예시입니다.
`SEARCH_BP B E` 명령 같은 경우 찾고자 하는 사용자의 이름을 userName이라고 했을때
"B <= userName <=E"  인 범위로 사용자에 대해서 모두 출력해야한다고 이해 했습니다.
하지만 예시에서 보면 E 보다 큰 Elsa, Emily, Erin에 대해서도 출력이 되었습니다.
제가 생각한 것처럼 "B <= userName <=E" 범위로 생각해도 될 지 궁금합니다.
아니라면  출력할 사용자이름의 범위를 정확하게 어떻게 설정해야할 지 궁금합니다.

**Comment by myungoh** [comment]
예시와 같이 첫 글자를 포함하도록 출력해주세요.

SEARCH_BP B E
--> B로 시작하는 이름부터 E로 시작하는 끝 단어까지 검색 후 출력

감사합니다.
