### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by kwYoohae** [myungoh/DS_Project_2_2021_2#16]
안녕하십니까 데이터구조실습을 듣고있는 유해찬 학생입니다.

다름이 아니라 질문이 생겨서 이슈올립니다.

혹시 과제 스펙에는 다음과 같이
![image](https://user-images.githubusercontent.com/74089271/140253157-6c2e86ea-cc69-4f96-ba65-0ea2e87ac3fd.png)
라고 명시되어 있는데 
![image](https://user-images.githubusercontent.com/74089271/140253192-dcca7d5f-7ad6-4dfc-af4f-256ec3db1962.png)
채점 기준표에서는 없어서 연락드렸습니다.

혹시 이번 과제에서도 메모리 누수에 대해서 채점을 하시는지 궁금합니다.

읽어주셔서 감사합니다.

**Comment by myungoh** [comment]
기본적인 메모리 누수는 확인합니다.  메모리 해제는 학생이 할 수 있는 만큼은 진행해주세요.
메모리 해제 안하면 감점합니다.
