### ISSUE TITLE
파일 입출력 및 코드 형태 질문

### ISSUE THREAD

**Issue by chopmozzi** [myungoh/DS_Project_2_2021_2#17]
안녕하세요 고생 많으십니다.
이번 프로젝트에 대해 궁금한 점이 있어 질문 드립니다.
파일 입출력 시 stl vector 사용해도 되나요?
int main(){
}
▽
int main()
{
}
이렇게 바꿔서 코드 작성을 해도 되나요?
고생 많으십니다. 감사합니다

**Comment by myungoh** [comment]
1. 네 가능합니다.
2. 네 가능합니다.
