### ISSUE TITLE
BpTreeNode.h 관련 질문있습니다.

### ISSUE THREAD

**Issue by jiwoo0629** [myungoh/DS_Project_2_2021_2#18]
BpTreeNode.h의 getDataMap() 함수 관련 질문입니다.
![image](https://user-images.githubusercontent.com/90768869/140398619-baff2d1e-92f3-4b8e-92b1-f9b2d2c9aed0.png)
리눅스 환경에서 코드를 실행하였더니 다음과 같은 warning이 계속하여 나왔습니다. visual studio 환경에서는 이상없이 작동했는데 리눅스 환경에서는 아예 작동이 되지 않았습니다. 이 코드는 skeleton 코드에 그대로 나와 있었던 코드인데 왜 문제가 생기는 것인지 알고 싶습니다.

**Comment by myungoh** [comment]
리눅스 g++ 컴파일러와 비주얼스튜디오 컴파일러 차이로 경고가 나오는 것 같습니다.

빌드시 warning이 뜨지만 실행하는데 문제는 없을 것입니다. 그대로 진행하시면 됩니다.
