### ISSUE TITLE
ADD 명령 질문

### ISSUE THREAD

**Issue by chanseobx** [myungoh/DS_Project_2_2021_2#19]
ADD명령을 실행할때
접종완료자 2회인 경우 예외처리를 한다고 되어있는데 에러코드를 출력하면 되는건가요?

만약 에러코드를 출력하는 경우라면 그 다음명령이 계속 실행되어야 하는건가요?

감사합니다.

**Comment by myungoh** [comment]
네. 에러 코드 출력 하고 다음 명령어 실행하시면 됩니다.
