### ISSUE TITLE
AVLTree.cpp Search 함수 관련 질문 있습니다.

### ISSUE THREAD

**Issue by jiwoo0629** [myungoh/DS_Project_2_2021_2#2]
제가 이해한 AVLTree.cpp의 Search 함수의 기능은
이름을 입력하여 데이터가 존재하면 그 사람의 정보를 출력하는 것인데
매개변수로 int형을 받는 것이 어떤 원리인지 이해가 되지 않습니다.
매개변수를 string형 이름으로 바꿔서 구현해도 되는 것인지 알고 싶습니다.

**Comment by jiwoo0629** [comment]
추가적으로 `AVLTree.cpp`의 `GetVector 함수`의 매개변수가 `vector<VaccinationData*>& v`이었는데, 이 매개변수를 사용하면 계속 오류가 생겨서 `vector<VaccinationData*>* v`로 바꾸었더니 오류가 생기지 않았습니다. 혹시 포인터를 가리키는게 아니라 주소값을 가져와야 하는 특별한 의도가 있는 것인지 알고 싶습니다.

**Comment by myungoh** [comment]
이름을 입력하는 것이 맞습니다.
매개변수를 string형으로 바꿔서 스켈레톤 코드를 업데이트 했습니다.

매개변수를 string으로 이름으로 바꿔서 구현하셔도 되고, 깃의 스켈레톤 코드를 다시 받아서 진행하셔도 됩니다.
감사합니다.
