### ISSUE TITLE
리눅스 환경 make 관련 질문있습니다.

### ISSUE THREAD

**Issue by jiwoo0629** [myungoh/DS_Project_2_2021_2#21]
![image](https://user-images.githubusercontent.com/90768869/140513243-79a8c1af-4394-4ca9-8b57-acaebd9226c1.png)
input_data.txt와 command.txt 파일을 통해 결과를 확인하기 위해
makefile의 SURC에 *.txt를 추가하고 `make`를 해보았습니다.
그 결과 위의 사진처럼 `collect2: error: ld returned 1 exit status`라는 오류가 발생했습니다.
무엇때문에 이런 오류가 발생하는지 알고싶습니다.
또, 만약 위의 방법이 잘못되었다면, input_data.txt와 command.txt 파일을 통해 결과를 확인할 수 있는 방법은 어떤 것이 있는지 궁금합니다.

**Comment by myungoh** [comment]
결과 확인은 log에 저장된 정보를 확인하시면 됩니다.
Makefile은 안건드리셔도 됩니다.

**Comment by jiwoo0629** [comment]
이 프로젝트 자체가 input_data.txt 파일과 command_txt 파일로부터 내용을 읽어와서 함수를 실행하는 구조인데, github를 clone해서 받은 skeleton 코드에는 위의 두 파일이 없습니다. 그래서 추가로 텍스트파일을 추가한 다음에 작동을 확인하려고 했는데 make를 하면 input_data.txt 파일과 command_txt 파일을 제외한 나머지 파일들만 make가 됐습니다. 이 문제를 어떻게 해결할 수 있을지 궁금합니다.

**Comment by myungoh** [comment]
텍스트 파일은 제공되지 않고 임의로 만드시면 됩니다. 그리고 manager.cpp에서 텍스트 파일을 로드해서 데이터를 읽어오면 됩니다.

**Comment by jiwoo0629** [comment]
./run을 통해 실행할 때, Killed라는 문구가 나오며 프로세스가 kill 되는 상황이 반복됩니다. 원인을 찾아보니 Out of Memory의 문제인 것 같은데 어떻게 해결할 수 있을지 궁금합니다.

**Comment by jiwoo0629** [comment]
input_data.txt 파일과 command.txt 파일을 임의로 만든 뒤에 ./run을 했더니, Killed라는 문구와 함께 실행이 되지를 않습니다. 원인을 분석해보니 out of memory의 문제인 것 같은데 어떻게 해결할 수 있을지 알고 싶습니다.

**Comment by myungoh** [comment]
그렇게만 말씀해주시면 알기 어렵고, 어느부분에서 종료가 되는지 확인이 필요합니다.
중간에 출력을 하면서 확인해보고 더 자세히 말해주세요.
