### ISSUE TITLE
LOAD관련 질문입니다.

### ISSUE THREAD

**Issue by jeminanda** [myungoh/DS_Project_2_2021_2#22]
프로젝트 스펙에서 input_data.txt에 들어가는 입력에 관한 내용 중
* 프로그램은 이름, 백신 명, 접종 횟수, 나이, 지역명 정보가 저장된 파일
input_data.txt 을 LOAD 명령어를 통해 읽어 해당 정보를 클래스에 저장한다.
* input_data.txt 에는 접종 대상자만 포함될 수 있다.
라고 적혀 있습니다. 
1. Tom 0 38 Seoul  과 같이 입력에 인자가 부족한 경우
2. Tom Pfizer 2 38 Seoul 과 같이 입력에 접종 완료 대상자가 입력된 경우
에러 처리를 따로 하는지 아니면 이런 입력이 없다고 가정하는지 질문드립니다.

**Comment by myungoh** [comment]
1. input_data.txt에 데이터의 인자가 부족한 경우는 없습니다.
2. 마찬가지로 이런 경우는 없습니다.
