### ISSUE TITLE
기본 제공되는 함수에 매개변수 추가 또는 수정이 가능한가요?

### ISSUE THREAD

**Issue by angrymusic** [myungoh/DS_Project_2_2021_2#26]
기본 제공되는 클래스 함수에서 매개변수 추가 또는 수정이 가능한가요?

**Comment by angrymusic** [comment]
추가적으로 BpTree에서 범위 검색을 하는 SearchRange()같은 경우 에러 발생을 인식하려면 void 가 아닌 bool 또는 int 형 함수로 바꿔줘야 할 것 같은데 함수형도 수정이 가능할까요?

**Comment by myungoh** [comment]
네. 가능합니다.
SearchRange() 내부에서 출력을 하셔도 되고, bool 타입으로 바꿔서 함수 밖에서 출력하셔도 되구요.
