### ISSUE TITLE
AVLTree.cpp 내의 Search 관하여 질문드립니다.

### ISSUE THREAD

**Issue by jyjin6340** [myungoh/DS_Project_2_2021_2#30]
안녕하세요. AVLTree.cpp를 구현하던 도중 궁금한 것이 생겨 질문드립니다.

AVLTree.cpp 내의 Search 함수를 구현할 때 STL queue 사용 가능한가요?

읽어주셔서 감사합니다.

**Comment by myungoh** [comment]
Search 함수를 구현할 때, queue를 어떤 용도로 사용하나요??

**Comment by jyjin6340** [comment]
level order traversal 형식으로 구현하려고 하는데, 그 때 사용할 예정입니다.

**Comment by myungoh** [comment]
레벨오더순회 방법으로 하지말고 특정 name을 AVL tree에서 찾을 때, 루트부터 이름이 작은지 큰지에 따라 왼쪽 노드, 오른쪽 노드로 따라가면서  같은 이름이 나올 때까지 탐색하시면 됩니다.

**Comment by jyjin6340** [comment]
네 답변 감사드립니다.
