### ISSUE TITLE
프로젝트 관련하여 질문있습니다.

### ISSUE THREAD

**Issue by quad0214** [myungoh/DS_Project_2_2021_2#32]
안녕하세요. 컴퓨터정보공학부 2020202094학번 백종천입니다.
 프로젝트에 다양한 부분에 질문이 있어, 이를 아래와 같이 항목으로 작성하였습니다.
 질문 수가 꽤 되어 항목으로 작성한 점과 양해부탁드립니다.
 
- **입출력 형식(명령 인자 포함)**
    1. 출력에서 구분하기 위해 붙이는 = 개수는 예제와 무조건 동일하게 해야하나요?
    2. 프로그램 시작시마다 log.txt 초기화해야 하나요?
    3. 동일한 백신 이름에 대소문자만을 달리하여 입력될 수도 있나요? 아니면 제안서에 작성된 것으로 고정된 상태로만 입력되나요?
    4. 인자나 input_data.txt에 적힌 나이나, 접종 횟수가 숫자 형태가 아닌 경우에 대해서 에러 처리해주어야 하나요?
    5. command.txt나 input_data.txt의 중간에 빈 줄이 나오면 에러를 처리해주어야 하나요?
    6. linux에서는 텍스트 파일의 마지막에 개행문자를 추가하는데, 이로 인해 빈 줄을 잘못된 명령어로 읽을 수 있습니다.(EXIT이 맨 마지막에 오지 않은 경우) 이에 이부분을 따로 처리해주어야 하는지 혹은 저번 프로젝트 처럼 무시해도 되는 지 궁금합니다.
    7. 이름의 경우 중복되지 않는 다고 작성되어있습니다. 이에 대소문자만 다른 중복되는 이름을 LOAD나 ADD로 추가하는 경우도 존재하지 않나요?
    
- **명령어**
    1. SEARCH_BP : 입력 문자 start, end의 순서가 start > end인 경우 에러 처리해야하나요?
    2. VPRINT : 출력 포맷 예시를 보면 Print_vector가 빈 경우에도 에러를 출력합니다. 같은 영역의 에러 코드 출력에서는 이에 대한 에러가 경우가 작성되어있지 않은데, 이 경우도 에러를 처리해야하나요? 이전 질문에서도 비슷한 내용이 있었는데 그때는 avl이 빈 경우에만 에러를 처리하라고 말씀하셔서 추가로 질문드립니다.
    3. ADD : 얀센 백신의 경우 ADD 명령어로 추가할 때 바로 접종 완료자가 됩니다. 그렇다면 B+ Tree에는 추가해주지 않는 것인가요?
    4. VLOAD : 추가로 avl 헤더에 queue stl 헤더를 추가하고, 이를 사용하여 구현하여도 되나요?

- **코드 의도 및 수정 질문**
    1. 스켈레톤 코드인 Manager.cpp에 Compare가 있는데 이름을 CompareA로 바꾸어 VPRINT의 A 조건 compare 함수로써 사용하여도 되나요? 이의 정확한 용도를 모르겠습니다.
    
- **bp tree**
    1. splitIndexNode 함수의 경우, 한 개의 bpTreeIndexNode만 분리하도록 구현하여도 되나요? 외부에서 반복을 돌면서 root까지 해당 함수를 호출하는 방향으로 구현하고자 하여 질문드립니다.
    
- **그 외**
    1. 다른 질문들에서 ADD_AVL에 대한 언급이 있는데 제안서에는 해당 내용이 존재하지 않습니다. 무시하여도 되는 것인가요?
    2. 제안서의 동작 예시 log.txt에서 끝 부분에 존재하는 VPRINT A와 VPRINT B가 잘못 작성되어있는 거 같습니다. 전자는 Elsa의 접종횟수가 적혀있지 않고, 후자는 얀센을 접종한 Elsa의 접종 횟수가 2로 적혀있습니다.

 최대한 기존의 질문과 겹치지 않도록 하였는데 혹시나 겹치는 질문이 있었다면 죄송합니다. 질문 읽어주셔서 감사합니다.

**Comment by myungoh** [comment]
입출력 형식(명령 인자 포함)
1. 아닙니다.
2. 네 맞습니다.
3. 제안서 작성된 고정된 상태로만 입력합니다.
4. 고려안하셔도 됩니다.
5. 그런 경우는 없다고 가정합니다.
6. 빈 줄은 없습니다. EXIT 명령어가 마지막에 들어오면 프로그램을 끝내면 됩니다.
7. 네 존재하지 않습니다.

**Comment by myungoh** [comment]
명령어
1. 고려하지 않아도 됩니다.
2. avl tree가 비어 있는 경우만 출력하시면 됩니다. avl tree가 비어있으면, print_vector가 비어있을 것이고 이 이외에는 고려하지 않아도 됩니다.
3. 둘 다 추가합니다.
4. 네 가능합니다.

**Comment by myungoh** [comment]
코드 의도 및 수정 질문
1. 네. CompareA, Compare B로 바꿔서 구현하시면됩니다.

bp tree
1. 네. 가능합니다.

그 외
1. B+tree를 구현을 제대로 하지 못한 경우 AVL tree 결과에 영향을 줄 수 있습니다. 추가 점수를 위해 ADD_AVL 명령어를 추가했습니다.  학생이 B+tree 구현에 문제가 있다고 생각하면 ADD_AVL 명령어에 대한 코드도 추가로 작성하시면 됩니다.

2. 감사합니다. 수정하겠습니다.
