### ISSUE TITLE
BpTreeNode.h Virtual function 질문입니다.

### ISSUE THREAD

**Issue by jeminanda** [myungoh/DS_Project_2_2021_2#33]
Skeleton Code의 BpTreeNode.h 함수 중에
virtual map<string, BpTreeNode*>* getIndexMap() { map<string, BpTreeNode*> m; return &m; }
virtual map<string, VaccinationData*> *getDataMap() { map<string, VaccinationData*> m; return &m; }
두 함수가 함수 내에서 생성한 임시객체 m의 주소값을 리턴하고 있어 컴파일 경고가 뜨는데, NULL값으로 return값을 바꿔주어도 될까요?

**Comment by myungoh** [comment]
네 바꾸셔도 됩니다.
