### ISSUE TITLE
BpTree searchDataNode 함수 관련 질문드립니다.

### ISSUE THREAD

**Issue by Jae211** [myungoh/DS_Project_2_2021_2#34]
현재 searchDataNode 함수는 DataNode에 입력된 string이 있는지 확인해서 return한 후, SEARCH_BP에서 다시 해당 string에 대한 map 원소만 찾아야 print해야 하는데, searchDataNode의 return 값을 VaccineData로 설정해서 SERACH_BP에서 해당 내용만 print하는 것은 안되나요?

**Comment by Jae211** [comment]
그리고 ADD 명령어 실행 시 B+Tree에 이름이 존재하지 않는 경우 접종 횟수를 1로 저장해야 하나요??

**Comment by myungoh** [comment]
SEARCH_BP의 이름 검색을 하는 경우 , searchDataNode 함수를 이용하시면 됩니다.
SEARCH_BP의 알파벳에 대한 영역 탐색 하는 경우, SearchRange 함수를 이용하시면 됩니다.

**Comment by myungoh** [comment]
네
