### ISSUE TITLE
VPRINT의 출력 포맷 예시에 질문있습니다.

### ISSUE THREAD

**Issue by quad0214** [myungoh/DS_Project_2_2021_2#35]
안녕하세요. 컴퓨터정보공학부 2020202094학번 백종천입니다.
VPRINT의 출력 포맷 예시에 질문이 있습니다.

 제안서의 p.8을 보면 VPRINT의 출력 포맷 예시 3에 Print_vector가 비어있는 경우에 오류 메시지를 출력합니다. 이때 Print_vector가 비어있다는 것은 곧 AVL tree가 비어있는 것이라고 생각하면 되나요?

 또한 AVL tree가 변화한 후에 VPRINT를 하기 전에는 무조건 VLOAD를 사용자가 실행한다고 가정하여도 되나요?  VPRINT는 단순히 Print_vector를 정렬하고 출력하는 것 뿐이고, VLOAD에서 Print_vector를 구성하는 것이기에 VLOAD 전에 VPRINT를 하면 AVL tree가 비어있지 않더라도 Print_vector를 출력할 수 없으리라 생각합니다. 지난번 질문에서 AVL tree가 비어있는 경우를 제외하고는 VPRINT의 예외처리를 하지 않아도 된다고 말씀하셔서 궁금해 질문드립니다.

**Comment by myungoh** [comment]
https://github.com/myungoh/DS_Project_2_2021_2/issues/32

avl tree가 비어 있는 경우만 출력하시면 됩니다. avl tree가 비어있으면, print_vector가 비어있을 것이고 이 이외에는 고려하지 않아도 됩니다.

**Comment by myungoh** [comment]
네네 VLOAD -> VPRINT 붙여서 테스트할거에요. AVL tree가 비어있는 경우만 하시면 됩니다.
