### ISSUE TITLE
질문 있습니다.

### ISSUE THREAD

**Issue by kwYoohae** [myungoh/DS_Project_2_2021_2#4]
안녕하세요 데이터구조 강의 수강중인 유해찬학생입니다.

질문이 있어서 이슈 올렸습니다.

- 첫 번째 질문입니다.
`VLOAD`를 할 때 `queue`든 `stack`이든 **재귀적인 방법을 사용하지 않고** 데이터를 불러온다고 하셨습니다.
이 때 `queue`나 `stack`를 사용하여 데이터를 받는 것은 어차피 `sort()`를 하기 때문에 `Level Order`든 `Pre Order`든 아무 방식이든 상관 없는 것인가요?

- 두 번째 질문입니다.
만약 `B+ tree`까지 구현을 한다면 `ADD_AVL`은 구현을 하지 않아도 되는 것인가요?

- 세 번째 질문입니다.
`SEARCH_BP`에서 인자를 **2개** 받았을 경우의 출력은 어떤 방식을 사용해도 상관이 없는 것인가요?
아니면 수업시간에 설명해주신 방법대로 꼭 구현해야하는 건가요?

- 네 번째 질문입니다.
![image](https://user-images.githubusercontent.com/74089271/139642222-3ed5faf9-e3e8-4992-9c67-ee3aa7bcfa15.png)
현재 채점 기준표에는 `B+ tree`관련 명령어가 없는데 `B+ tree`를 구현하는 것에 대해서는 어떻게 채점을 하실 계획이신가요?

- 다섯 번째 질문입니다.
![image](https://user-images.githubusercontent.com/74089271/139644178-ec49ef60-c445-4f82-b1a1-64324328bdd7.png)
이렇게 현재 명시되어있는데 저는 `Manger::ADD()` 함수에 인자를 따로 설정해주었는데
이런점들이 모두 불가한가요? 

읽어주셔서 감사합니다.

**Comment by myungoh** [comment]
1. 네 상관없습니다.
2. 네. 그런데, B+tree가 잘못된 경우 AVL tree 구현에 영향을 줄 수 있을 것 같아요.
    그런 경우를 대비하는 차원에서 ADD_AVL도 있으면 더 좋을거라 생각합니다.
3. 결과만 동일하게 나오면 상관없습니다.
4. PRINT_BP와 SEARCH_BP로 채점을 합니다.
5. Manager::ADD()는 인자를 따로 추가하셔도 됩니다.
감사합니다.
