### ISSUE TITLE
명령어 EXIT에 관한 질문

### ISSUE THREAD

**Issue by merryberry01** [myungoh/DS_Project_2_2021_2#41]
안녕하세요,
현재 제안서에 요구되어 있는 대로 명령어 인자에 대한 예외(개수가 부족하거나 초과할 경우)를 처리했습니다.
그런데 EXIT같은 경우는 인자가 없는 명령어인데, 
불필요한 인자가 입력되면 에러 코드를 출력해야 하나, 제안서에는 EXIT의 에러 코드가 명시되어 있지 않습니다.
EXIT의 경우에는 인자에 대한 예외는 처리하지 않아도 되는지 궁금합니다.

**Comment by myungoh** [comment]
EXIT 명령어 예외처리는 안해도 됩니다. 감사합니다.
