### ISSUE TITLE
LOAD 관련 질문 있습니다

### ISSUE THREAD

**Issue by JeonSeungGwon** [myungoh/DS_Project_2_2021_2#5]
LOAD를 할 때 

- 텍스트 파일이 존재하지 않는 경우
- 텍스트 파일 안에 데이터가 존재하지 않는 경우
- B+ Tree가 존재하는 경우

위와 같이 3가지 경우에 대해서 에러 코드를 출력하게 되어있는데,

만약 input_data.txt에 5가지 정보 중 어느 하나라도 없어도 똑같이 에러 코드를 출력해야 하는 건지 궁금합니다.

**Comment by myungoh** [comment]
그런 경우는 고려하지 않으셔도 됩니다.
감사합니다.
