### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by kwYoohae** [myungoh/DS_Project_2_2021_2#6]
안녕하세요 데이터구조실습 과목 수강중인 유해찬학생입니다.

질문이 있어서 연락드렸습니다.

**[질문 1]**

![image](https://user-images.githubusercontent.com/74089271/139660438-ef0f0abf-21ec-433d-9a96-6765a9d4914f.png)
`VPRINT`부분에서 에러 코드 출력 부분에서 `AVL tree`가 비어있는 경우가 맞는지 궁금합니다.

저는 `VPRINT`는 `Print_vector`에 저장된 데이터를 조건 A,B 에 따라 정렬을 하고 출력하는 것으로 알고 있습니다.

그런데 `VPRINT`를 할 때 `VLOAD`를 하지 않거나 `AVL tree`는 비어있지 않아도 `Print_vector`에 저장된 데이터가 없다면
`VPRINT`를 할 수 없습니다.

혹시 `AVL tree`가 비어있을 경우가 맞을까요? `Print_vector`가 비어있는 경우가 맞을까요?

**[질문 2]**

만약 `ADD_AVL`에서 오류가 생기면 에러코드는 어떻게 해야할까요?

읽어주셔서 감사합니다

**Comment by myungoh** [comment]
1. 맞는 말씀이긴 하지만,  그 부분은 고려하지 않아도 됩니다. AVL tree가 비어있는 경우에만 VPRINT를 에러 출력 하시면 됩니다.
2. 에러코드는 고려안해도 됩니다.
