### ISSUE TITLE
DS_Project_2_2021_2.pdf 동작 예시 질문

### ISSUE THREAD

**Issue by chanseobx** [myungoh/DS_Project_2_2021_2#7]
1.
마지막 command VPRINT B 했을 때 VPRINT A와 다르게 TOM이 추가가 된걸로 보이는데, ADD로 TOM을 더하고 VLOAD 한 것인데
VLOAD가 파일에서 생략된 것인가요? 아니면 VLOAD를 하지 않아도 백신접종완료자이기 때문에 자동으로 로드된것인가요?

2.
ADD 동작예시에서 마지막 TOM은 기존에 ADD명령과 달리 백신접종횟수가 보이는데, 백신접종완료자는 횟수를 추가로 표시되게 구현하는것인가요?

감사합니다.

**Comment by myungoh** [comment]
1. 아니요. 예제가 잘못됐네요.
2. 아니요. 잘못된 예시입니다.

Program implementation이 정확하니, 이를 보고 진행해주세요. 
밑의 것은 동작 예시이니 참고만 해주세요.
자료는 수정해서 업로드하겠습니다.
