### ISSUE TITLE
질문 있습니다

### ISSUE THREAD

**Issue by kwYoohae** [myungoh/DS_Project_2_2021_2#8]
안녕하십니까 데이터구조실습 과목을 수강하고있는 유해찬 학생입니다.

궁금한점이 생겨서 연락드렸습니다.

**[문제1]**

![image](https://user-images.githubusercontent.com/74089271/139772899-52cec6e3-319b-41e2-a28d-4e5824537106.png)
다음은 PDF에 나와있는 예시인데 현재 `ADD`를해서 `Tom`이라는 접종완료자가 늘어났습니다

그 후 `VPRINT B`를 시행하는데 `VPRINT`는 `Print_Vecotr`에 있는 정보를 정렬하여 출력하는 것으로 알고 있습니다.

혹시 `ADD`를 해서 접종완료자가 생기면 `AVL tree`에 저장되고 자동으로 `Print_vector`에 들어가는 것인가요? 

아니면 예제가 잘못된것인지 궁금해서 연락드렸습니다.

읽어주셔서 감사합니다

**Comment by myungoh** [comment]
ver6으로 다운받아서 진행하시면 됩니다.

https://github.com/myungoh/DS_Project_2_2021_2/issues/7
