### ISSUE TITLE
B+ tree 관련 질문있습니다. 

### ISSUE THREAD

**Issue by rhrkdus** [myungoh/DS_Project_2_2021_2#9]
BpTree 에서 SearchRange()함수가 어떤 용도로 쓰이는지 궁금합니다.

**Comment by myungoh** [comment]
마지막 리프 노드의 영역(start, end) 탐색하여 출력할 때 사용합니다.

**Comment by rhrkdus** [comment]
B+ searchDataNode 함수에서 해당 이름을 찾을 때 map. find() 함수를 사용하나요?

**Comment by myungoh** [comment]
사용하셔도 되며, map size 만큼 이터레이션 돌면서 찾으셔도 됩니다.
